name: Android Dev Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x ./android/gradlew
      - name: Build APK
        run: cd android && ./gradlew assembleDebug
      - name: Upload APK to Releases
        uses: actions/upload-release-asset@v1
        with:
          asset_path: android/app/build/outputs/apk/debug/app-debug.apk
          asset_name: app-debug.apk
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
